; Each new term in the Fibonacci sequence is generated by adding the previous two terms.
; By starting with 1 and 2, the first 10 terms will be:
; 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
; By considering the terms in the Fibonacci sequence whose values do not exceed four million,
; find the sum of the even-valued terms.


;=> (sumValues)
;4613732


(defn fib [n]
  (cond 
    (= n 0) 0
    (= n 1) 1
    (= n 2) 1
    :else
    (+ (fib (- n 1)) (fib (- n 2))))
)

(defn sumValues []
  ;(reduce + (take-while (partial > 4000000) (fib (iterate inc 0)))) 
  ;(reduce + (take-while (partial > 1000) (iterate inc 0)))
  ;(reduce + (take-while #(< (fib %) 40000000 ) (iterate inc 0)))
  (reduce + (filter even? (take-while #(< % 4000000) (map #(fib %) (iterate inc 0)))))
  
)
